development:
  adapter: postgresql
  encoding: unicode
  database: praveen
  pool: 5
  username: postgres
  password: 5436
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: praveen
  pool: 5
  username: postgres
  password: 5436
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: praveen
  pool: 5
  username: postgres
  password: 5436